name: reusable-code_quality_check
on:
  workflow_call:
    outputs:
      tests-failed:
        description: "Specifies whether the given commands failed"
        value: ${{ jobs.test.outputs.TESTS_FAILED }}
env:
  # Log color in the test output
  FORCE_COLOR: 1
jobs:
  lint:
    timeout-minutes: 2
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout code
        uses: actions/checkout@v3
      -
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      -
        name: Clean install with dev dependencies
        run: |
          npm ci
      -
        name: Linting
        run: |
          npm run lint
  test:
    timeout-minutes: 2
    runs-on: ubuntu-latest
    environment: testing
    outputs:
      TESTS_FAILED: ${{ steps.failure-test.outputs.TESTS_FAILED }}
    steps:
      -
        name: Checkout code
        uses: actions/checkout@v3
      -
        name: Pull images
        run: docker compose -f scripts/docker-compose.test.yml pull
      -
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      -
        name: Clean install
        run: |
          npm ci --omit=dev
      -
        name: Run tests
        id: run-tests
        run: |
          npm run test
      -
        name: Upload report if tests fail
        if: ${{ failure() && steps.run-tests.outcome == 'failure' }}
        uses: actions/upload-artifact@v3
        id: upload-report
        with:
          name: test-report
          path: ./playwright-report
      -
        name: Set Output if tests fail
        id: failure-test
        if: ${{ failure() && steps.upload-report.outcome == 'success' }}
        run: |
          echo "TESTS_FAILED=true" >> $GITHUB_OUTPUT
      
